### ISSUE TITLE
#15 - FD - Creating an account with negative balance

### ISSUE THREAD

**Issue by kstrones** [abahrema/ser316labcr#14]
When creating a new account starting with a negative value there is no popup to tell the user the account could not be created however there is an exception that gets thrown to the console.

Filename: ServerSolution.java/newAccount
Line: 74
Category: Functional Defect

kstrones Issue # 10
abahrema Issue #
swDunning Issue #8

**Comment by swdunningASU** [comment]
Everything taken care of for issue #15
