### ISSUE TITLE
#31 – FD – ServerSolution.java

### ISSUE THREAD

**Issue by abahrema** [abahrema/ser316labcr#36]
In ServerSolution.java Line 118 The file's SaveAccounts method doesn't work, nor save files. This si because it uses a for loop to iterate through elements, but since we are using a hash set this won't work because we must use a foreach loop to iterate through elements. 

Category: Functional Defect

abahrema Issue # 20
kstrones Issue # N/A
swDunning Issue #

**Comment by swdunningASU** [comment]
issue #31 finished.
